services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: prod
    container_name: backend
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    networks:
      - webapp
    environment:
      - PORT=8080
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      target: prod
    container_name: frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    networks:
      - webapp
    environment:
      - PORT=3000
    restart: unless-stopped

networks:
  webapp:
    driver: bridge