name: Deploy with Docker Compose to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create private key file
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" | tr -d '\r' > private_key.pem
          chmod 600 private_key.pem
      
      - name: Deploy to EC2 with Docker Compose
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@ec2-51-20-103-117.eu-north-1.compute.amazonaws.com << 'EOF'
            # Navigate to project directory
            cd ~/go_stack/
            
            # Pull latest code
            git pull
            
            # Build and restart containers
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
            
            # Prune unused images to save space
            docker image prune -f
            
            # Check if containers are running
            docker-compose ps
          EOF
      
      - name: Clean up private key
        run: rm -f private_key.pem