name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to AWS
        env:
          AWS_HOST: ${{ secrets.AWS_HOST }}
          AWS_USER: ${{ secrets.AWS_USER }}
          AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
        run: |
          ssh -i $AWS_SSH_KEY ubuntu@ec2-51-20-103-117.eu-north-1.compute.amazonaws.com 'cd ./go_stack && git pull && docker-compose up -d'
