name: Deploy to AWS

on:
  push:
    branches:
      - main  # Trigger on push to main branch (adjust accordingly)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create private key file
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" | tr -d '\r' > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy with Docker Compose
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@ec2-51-20-103-117.eu-north-1.compute.amazonaws.com << EOF
            cd go_stack/
            git pull
            docker-compose up -d
          EOF

      - name: Clean up private key
        run: |
          rm private_key.pem
