name: Deploy to AWS

on:
  push:
    branches:
      - main  # Trigger on push to main branch (adjust accordingly)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "$AWS_SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to AWS
        run: |
          ssh -i private_key.pem ubuntu@ec2-51-20-103-117.eu-north-1.compute.amazonaws.com << EOF
            'cd go_stack/ && git pull && docker-compose up -d'
          EOF

      - name: Clean up private key
        run: |
          rm private_key.pem
