name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          # Decode the SSH private key and save it to a file
          echo "$AWS_SSH_KEY" | base64 --decode > /tmp/aws_private_key.pem
          # Set appropriate file permissions
          chmod 600 /tmp/aws_private_key.pem

      - name: SSH into AWS and deploy
        run: |
          # Use SSH with the decoded key
          ssh -i /tmp/aws_private_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@your-ec2-ip \
            'cd ./go_stack && git pull && docker-compose up -d'